// Simple PDF generation utility for tutorial materials
// In a real app, you would use a library like jsPDF or generate PDFs on the server

export const generateTutorialPDF = (tutorial) => {
  // Create a simple HTML content for the PDF
  const content = `
    <!DOCTYPE html>
    <html>
    <head>
      <title>${tutorial.title} - Course Notes</title>
      <style>
        body { font-family: Arial, sans-serif; margin: 40px; }
        .header { text-align: center; margin-bottom: 30px; }
        .title { font-size: 24px; color: #1890ff; margin-bottom: 10px; }
        .subtitle { font-size: 16px; color: #666; }
        .section { margin: 20px 0; }
        .section h3 { color: #333; border-bottom: 2px solid #1890ff; padding-bottom: 5px; }
        .info { background: #f5f5f5; padding: 15px; border-radius: 5px; margin: 15px 0; }
        .objectives { background: #e6f7ff; padding: 15px; border-radius: 5px; margin: 15px 0; }
        .notes { background: #fff7e6; padding: 15px; border-radius: 5px; margin: 15px 0; }
      </style>
    </head>
    <body>
      <div class="header">
        <div class="title">${tutorial.title}</div>
        <div class="subtitle">Ethiopian Tutorial App - Course Materials</div>
      </div>
      
      <div class="info">
        <h3>Course Information</h3>
        <p><strong>Category:</strong> ${tutorial.category}</p>
        <p><strong>Difficulty:</strong> ${tutorial.difficulty}</p>
        <p><strong>Duration:</strong> ${tutorial.duration}</p>
        <p><strong>Rating:</strong> ${tutorial.rating}/5 stars</p>
      </div>
      
      <div class="section">
        <h3>Description</h3>
        <p>${tutorial.description}</p>
      </div>
      
      <div class="objectives">
        <h3>Learning Objectives</h3>
        <ul>
          <li>Master the fundamental concepts of ${tutorial.category?.toLowerCase() || 'Ethiopian Culture'}</li>
          <li>Understand the cultural significance and context</li>
          <li>Practice with hands-on exercises and examples</li>
          <li>Apply knowledge in real-world scenarios</li>
        </ul>
      </div>
      
      <div class="notes">
        <h3>Key Points to Remember</h3>
        <ul>
          <li>Take notes during the video lesson</li>
          <li>Practice regularly for better retention</li>
          <li>Don't hesitate to review difficult sections</li>
          <li>Connect with other learners for discussion</li>
        </ul>
      </div>
      
      <div class="section">
        <h3>Additional Resources</h3>
        <ul>
          <li>Amharic Alphabet Chart</li>
          <li>Cultural Context Guide</li>
          <li>Practice Exercises</li>
          <li>Audio Pronunciation Guide</li>
        </ul>
      </div>
      
      <div style="margin-top: 40px; text-align: center; color: #666; font-size: 12px;">
        Generated by Ethiopian Tutorial App - ${new Date().toLocaleDateString()}
      </div>
    </body>
    </html>
  `;
  
  // Create a blob and download
  const blob = new Blob([content], { type: 'text/html' });
  const url = URL.createObjectURL(blob);
  
  const link = document.createElement('a');
  link.href = url;
  link.download = `${tutorial.title.replace(/[^a-z0-9]/gi, '_').toLowerCase()}_notes.html`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
};

export const generateCertificate = (tutorial, userName) => {
  const content = `
    <!DOCTYPE html>
    <html>
    <head>
      <title>Certificate of Completion - ${tutorial.title}</title>
      <style>
        body { font-family: 'Times New Roman', serif; margin: 0; padding: 40px; text-align: center; }
        .certificate { border: 5px solid #1890ff; padding: 40px; background: #fafafa; }
        .title { font-size: 28px; color: #1890ff; margin-bottom: 20px; font-weight: bold; }
        .subtitle { font-size: 18px; color: #666; margin-bottom: 30px; }
        .name { font-size: 24px; color: #333; margin: 20px 0; font-weight: bold; }
        .course { font-size: 20px; color: #1890ff; margin: 20px 0; }
        .date { font-size: 16px; color: #666; margin-top: 30px; }
        .signature { margin-top: 40px; }
        .signature-line { border-top: 2px solid #333; width: 200px; margin: 0 auto; }
        .signature-text { font-size: 14px; color: #666; margin-top: 5px; }
      </style>
    </head>
    <body>
      <div class="certificate">
        <div class="title">CERTIFICATE OF COMPLETION</div>
        <div class="subtitle">Ethiopian Tutorial App</div>
        
        <div class="name">${userName}</div>
        
        <div>has successfully completed the course</div>
        
        <div class="course">"${tutorial.title}"</div>
        
        <div class="date">Completed on ${new Date().toLocaleDateString()}</div>
        
        <div class="signature">
          <div class="signature-line"></div>
          <div class="signature-text">Instructor Signature</div>
        </div>
      </div>
    </body>
    </html>
  `;
  
  const blob = new Blob([content], { type: 'text/html' });
  const url = URL.createObjectURL(blob);
  
  const link = document.createElement('a');
  link.href = url;
  link.download = `${userName.replace(/[^a-z0-9]/gi, '_').toLowerCase()}_certificate_${tutorial.title.replace(/[^a-z0-9]/gi, '_').toLowerCase()}.html`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
};
